project:
  name: protein-function-prediction
  seed: 42

paths:  # paths are relative to the project's root folder
  data_dir: data/
  dataset_raw: data/dataverse_files.zip
  train_data: data/train/train.csv
  test_data: data/test/test.csv
  save_dir: outputs/
  log_dir: logs/
  model_checkpoint: checkpoints/

data:
  batch_size: 64
  max_seq_len: 2000
  shuffle: true
  validation_split: 0.15
  num_classes: 5

sample_model_config:
  name: MyMLP
  input_size: [100]
  dropout_rate: 0.3
  training:
    epochs: 50
    learning_rate: 0.001
    optimizer: adam
    weight_decay: 0.0001
    early_stopping:
      enabled: true
      patience: 5

evaluation:
  metrics: [accuracy, f1_score]

hyperopt:
  enabled: false
  max_trials: 50
  sampler: tpe
  pruner: hyperband

