ProtTransMLP:
  batch_norm: true
  dataset_type: ProtTrans
  dropout_rate: 0.0
  embedding_dim: 1024
  hidden_dims:
  - 1024
  - 128
  loss: cross_entropy
  n_hidden: 2
  training:
    early_stopping:
      min_delta: 0.01
      patience: 9
    epochs: 30
    learning_rate: 1.6426745407354637e-05
    optimizer: adamw
    weight_decay: 1.3296139485485973e-05
data:
  batch_size: 256
  max_seq_len: 2000
  num_classes: 5
  shuffle: true
  validation_split: 0.15
evaluation:
  metrics:
  - accuracy
  - f1_score
hyperopt:
  min_resource: 4
  num_trials: 60
paths:
  data_dir: data/
  dataset_raw: data/dataverse_files.zip
  log_dir: logs/
  model_checkpoint: checkpoints/
  save_dir: outputs/
project:
  name: protein-function-prediction
  seed: 42
